version: '3'
services:
    db:
        image: mysql:5.7
        volumes:
            - "db-data:/var/lib/mysql"
        ports:
            - "3306:3306"
        networks:
            - monocoque
        env_file:
            - config.env
    nginx:
        image: nginx:latest
        expose:
            - "80"
            - "443"
        volumes:
            - ${PWD}/config/nginx/nginx.conf:/etc/nginx/conf.d/
            - ${PWD}/config/nginx/site.nginx.conf:/etc/nginx/conf.d/
        networks:
            - monocoque
        env_file:
            - config.env
        depends_on:
            - php
    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - monocoque
volumes:
    db-data: {}
networks:
    monocoque: {}
